Wrap tasks with start and end messages, make internals quieter

diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -10,17 +10,30 @@ type_exists() {
 
 # Compares git hashes
 check_version() {
-  cd $WW_DIR && git fetch
+  cd $WW_DIR && git fetch --quiet
+  # Version
+  VER_LOCAL=$(git rev-parse @{0})
+  VER_REMOTE=$(git rev-parse @{u})
+  VER_BASE=$(git merge-base @{0} @{u})
   if [ $VER_LOCAL = $VER_REMOTE ]; then
     :
   elif [ $VER_LOCAL = $VER_BASE ]; then
     display_status_primary "INFO" "Updating WorkWork..."
-    cd $WW_DIR && git pull -q origin master
+    cd $WW_DIR && git pull --quiet origin master
+    # Start the command over with the updated files
+    exec "$0" "$@"
   elif [ $VER_REMOTE = $VER_BASE ]; then
     display_status_primary "WARN" "Please push your changes to the remote..."
   else
-    display_status_primary "WARN" "Can't update due to local changes..."
+    display_status_primary "ERROR" "Can't update WorkWork due to local changes..."
   fi
+}
+
+# Grabs sudo and tries to keep it alive
+# Credit: https://gist.github.com/cowboy/3118588
+check_sudo() {
+  sudo -v -p 'Enter your sudo password:'
+  while true; do sudo -n true; sleep 40; kill -0 "$$" || exit; done 2>/dev/null &
 }
 
 # Ensure at least one command is supplied
@@ -43,6 +56,7 @@ install_app() {
 
 setup_site() {
   if [ $1 = "dd" ]; then
+    SITE_FULL_NAME="Debrief Daily"
     SITE_NAME="debriefdaily"
     SITE_DIR="${HOME}/workspace/mwn-${SITE_NAME}"
     SITE_PROD_URL="www.${SITE_NAME}.com"
@@ -81,4 +95,15 @@ check_platform() {
     echo "FATAL: Could not detect the platform!"
     exit
   fi
+}
+
+# Save cursor
+save_cursor() {
+  tput sc
+}
+
+# Restore cursor and erase to end of line
+replace_line() {
+  tput rc
+  tput el
 }
